name: check and upload

on:
  pull_request:
  push:
    branches:
      - github

jobs:
  tox_test:
    name: Tox test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env: [py36, py37, py38, py39]
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@master
      with:
        tox_env: ${{ matrix.tox_env }}
  upload:
    needs: [tox_test]
    runs-on: ubuntu-latest
    - name: install jfrog
      run: curl -fL https://getcli.jfrog.io | sh
    - name: upload to jfrog
      run: echo "upload..."
