name: Upload library to jFrog artifactory

on:
  push:
    branches:
      - github

jobs:
  upload:
    name: Upload lib to artifactory
    runs-on: ubuntu-latest
    steps:
      - name: install jfrog
        run: curl -fL https://getcli.jfrog.io | sh
