name: upload

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: python3 -m pip install --user --upgrade setuptools wheel
      - name: build
        run: python3 setup.py sdist bdist_wheel
      - name: install jfrog
        run: curl -fL https://getcli.jfrog.io | sh
      - name: upload to jfrog
        run: ls -al dist && ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --access-token $ARTIFACTORY_PASSWORD --interactive=false &&
          ./jfrog rt u --build-name=Crypto-Blockchain-PYPI --build-number=${{ github.run_id }} --flat=true "dist/*" "$ARTIFACTORY_NAME"